version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: devsu
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      springboot-mysql-net:
  mysqldb2:
    container_name: mysqldb2
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: devsu-cuenta
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      springboot-mysql-net-cuenta:
  redis:
    image: redis:3.2.5
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/dаta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
      
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq-local
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"    # Puerto estándar de RabbitMQ
      - "15672:15672"  # Puerto para la interfaz de gestión (HTTP)
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 1234  
  

networks:
  springboot-mysql-net:
  springboot-mysql-net-cuenta: